const SOURCE_HEADERS = [
  'No. Invoice Asal',
  'Kode Barang',
  'Harga Setelah PPN',
  'Sum of Jumlah',
  'Sum of Total Harga Produk Setelah PPN',
  'Nama Pelanggan',
  'MP',
  'Memo Header',
  'Tgl Faktur',
  'No. Faktur',
  'Display Name',
  'Customer Internal ID',
  'Customer ID',
  'Date',
  'Term Transaction',
  'ID Term',
  'Due Date',
  'Require eFaktur',
  'Currency',
  'Exchange Rate',
  'Item',
  'ID Item',
  'QUANTITY',
  'UNIT PRICE',
  'Total',
  'DPP',
  'Tax Amount',
  'Location',
  'Department',
  'Activity ID',
];

const REQUIRED_HEADERS = [
  'No. Invoice Asal',
  'No. Faktur',
  'Tgl Faktur',
  'Customer ID',
  'Kode Barang',
  'QUANTITY',
  'UNIT PRICE',
  'Harga Setelah PPN',
  'Location',
];

const FIELD_MAP = {
  INVOICENO: 'No. Faktur',
  INVOICEDATE: 'Tgl Faktur',
  CUSTOMERID: 'Customer ID',
  SALESINVOICEID: 'No. Invoice Asal',
  WAREHOUSEID: 'Location',
  DESCRIPTION: 'Memo Header',
  RATE: 'Exchange Rate',
  CURRENCYNAME: 'Currency',

  ITEMNO: 'Kode Barang',
  ITEMOVDESC: 'Item',
  QUANTITY: 'QUANTITY',
  UNITPRICE: 'UNIT PRICE',
  BRUTTOUNITPRICE: 'Harga Setelah PPN',
  WAREHOUSEID_ITEM: 'Location',
  INVID: 'No. Invoice Asal',
};

module.exports = {
  databaseCode: 'KATO',
  transactionCode: 'SALES_RETURN',
  sheetName: 'Data Retur',
  headerRow: 0,
  dataStartRow: 1,
  sourceHeaders: SOURCE_HEADERS,
  requiredHeaders: REQUIRED_HEADERS,
  fieldMap: FIELD_MAP,
  defaultBranchCode: '',
  defaults: {
    DELIVERYORDERID: '',
    SALESMANID: '',
    TAX1CODE: '',
    TAX1RATE: '',
    TAX2CODE: '',
    TAX2RATE: '',
    INCLUSIVETAX: '1',
    CUSTOMERISTAXABLE: '',
    CASHDISCOUNT: '',
    CASHDISCPC: '',
    GLYEAR: '',
    GLPERIOD: '',
    INVOICESEQ: '',
    ITEMUNIT: '',
    UNITRATIO: '',
    ITEMDISCPC: '',
    TAXCODES: '4',
    DOID_ITEM: '',
  },
};
