const SOURCE_HEADERS = [
  'Nama Panggilan Toko BigSeller',
  'Kode Barang',
  'Harga Setelah Diskon',
  'Sum of Jumlah',
  'Sum of Total Harga Produk',
  'Nama Pelanggan',
  'Tgl Faktur',
  'Urut',
  'Reversed',
  'No. Faktur',
  'Display Name',
  'Accurate Inv. No.',
  'Customer Internal ID',
  'Customer ID',
  'Legal Name',
  'Internal ID Employee',
  'Sales Name',
  'Date',
  'Term Transaction',
  'ID Term',
  'Due Date',
  'Required E-Faktur',
  'Kode Jenis Transaksi',
  'Faktur No',
  'AR Account',
  'Currency',
  'Exchange Rate',
  'Memo Header',
  'Item',
  'ID Item',
  'QUANTITY',
  'UNIT PRICE',
  'Total',
  'Tax Code',
  'DPP',
  'Tax Amount',
  'Location',
  'Department',
  'Class',
];

const REQUIRED_HEADERS = [
  'Accurate Inv. No.',
  'Tgl Faktur',
  'Customer ID',
  'Sales Name',
  'Term Transaction',
  'AR Account',
  'Currency',
  'Exchange Rate',
  'Required E-Faktur',
  'Display Name',
  'Location',
  'Urut',
  'Kode Barang',
  'QUANTITY',
  'UNIT PRICE',
];

const FIELD_MAP = {
  INVOICENO: 'Accurate Inv. No.',
  INVOICEDATE: 'Tgl Faktur',
  CUSTOMERID: 'Customer ID',
  TERMSID: 'Term Transaction',
  WAREHOUSEID: 'Location',
  SALESMANID: 'Sales Name',
  DESCRIPTION: 'Memo Header',
  SHIPDATE: 'Tgl Faktur',
  TAXDATE: 'Tgl Faktur',
  RATE: 'Exchange Rate',
  FISCALRATE: 'Exchange Rate',
  ARACCOUNT: 'AR Account',
  CURRENCYNAME: 'Currency',
  TAXFORMNUMBER: 'Faktur No',
  CUSTOMERISTAXABLE: 'Required E-Faktur',
  
  KEYID: 'Urut',
  ITEMNO: 'Kode Barang',
  ITEMOVDESC: 'Display Name',
  ITEMUNIT: 'UOM',
  QUANTITY: 'QUANTITY',
  UNITPRICE: 'UNIT PRICE',
  WAREHOUSEID_ITEM: 'Location',
};

module.exports = {
  databaseCode: 'KATO',
  transactionCode: 'SALES_INVOICE',
  sheetName: 'Data SI',
  headerRow: 0,
  dataStartRow: 1,
  sourceHeaders: SOURCE_HEADERS,
  requiredHeaders: REQUIRED_HEADERS,
  fieldMap: FIELD_MAP,
  defaultBranchCode: '',
};
