const SOURCE_HEADERS = [
  'Nama Panggilan Toko BigSeller',
  'Kode Barang',
  'Harga Setelah Diskon',
  'Sum of Jumlah',
  'Sum of Total Harga Produk',
  'Nama Pelanggan',
  'Tgl Faktur',
  'Urut',
  'Reversed',
  'No. Faktur',
  'Display Name',
  'Accurate Inv. No.',
  'Customer Internal ID',
  'Customer ID',
  'Legal Name',
  'Internal ID Employee',
  'Sales Name Netsuite',
  'Date',
  'Term Transaction',
  'ID Term',
  'Due Date',
  'Required E-Faktur',
  'Kode Jenis Transaksi',
  'Faktur No',
  'AR Account',
  'Currency',
  'Exchange Rate',
  'Memo Header',
  'Item',
  'ID Item',
  'QUANTITY',
  'UNIT PRICE',
  'Total',
  'Tax Code',
  'DPP',
  'Tax Amount',
  'Location',
  'Department',
  'Class',
];

const REQUIRED_HEADERS = [
  'Accurate Inv. No.',
  'Tgl Faktur',
  'Customer ID',
  'Kode Barang',
  'QUANTITY',
  'UNIT PRICE',
];

const FIELD_MAP = {
  INVOICENO: 'Accurate Inv. No.',
  INVOICEDATE: 'Tgl Faktur',
  CUSTOMERID: 'Customer ID',
  TERMSID: 'Term Transaction',
  WAREHOUSEID: 'Location',
  SALESMANID: 'Sales Name Netsuite',
  DESCRIPTION: 'Memo Header',
  SHIPDATE: 'Date',
  TAXDATE: 'Date',
  RATE: 'Exchange Rate',
  FISCALRATE: 'Exchange Rate',
  ARACCOUNT: 'AR Account',
  CURRENCYNAME: 'Currency',
  TAXFORMNUMBER: 'Faktur No',
  TAXFORMCODE: 'Kode Jenis Transaksi',

  KEYID: 'Urut',
  ITEMNO: 'Kode Barang',
  QUANTITY: 'QUANTITY',
  UNITPRICE: 'UNIT PRICE',
  TAXCODES: 'Tax Code',
  WAREHOUSEID_ITEM: 'Location',
};

module.exports = {
  databaseCode: 'KATO',
  transactionCode: 'SALES_INVOICE',
  sheetName: 'Data SI',
  headerRow: 0,
  dataStartRow: 1,
  sourceHeaders: SOURCE_HEADERS,
  requiredHeaders: REQUIRED_HEADERS,
  fieldMap: FIELD_MAP,
  defaultBranchCode: '',
};
