const SOURCE_HEADERS = [
  'Sales Invoice Internal ID',
  'Sales Invoice',
  'Jumlah Pelunasan',
  'Nama Pelanggan',
  'MP',
  'Memo Header',
  'TGL PELUNASAN',
  'No Pelunasan',
  'Jumlah Pelunasan1',
  'Customer Internal ID',
  'Customer ID',
  'Date',
  'Term Transaction',
  'ID Term',
  'Due Date',
  'Require eFaktur',
  'Currency',
  'Exchange Rate',
  'Location',
  'Department',
  'Activity ID',
];

const REQUIRED_HEADERS = [
  'Sales Invoice',
  'Jumlah Pelunasan',
  'TGL PELUNASAN',
  'No Pelunasan',
  'Jumlah Pelunasan1',
  'Customer ID',
  'Currency',
  'Exchange Rate',
];

const FIELD_MAP = {
  SEQUENCENO: 'No Pelunasan',
  PAYMENTDATE: 'TGL PELUNASAN',
  BILLTOID: 'Customer ID',
  RATE: 'Exchange Rate',
  DESCRIPTION: 'Memo Header',
  CURRENCYNAME: 'Currency',

  ARINVOICEID: 'Sales Invoice',
  PAYMENTAMOUNT: 'Jumlah Pelunasan1',
  SOURCE_CHEQUEAMOUNT: 'Jumlah Pelunasan',
};

module.exports = {
  databaseCode: 'KATO',
  transactionCode: 'PAYMENT',
  sheetName: 'Data Payment',
  headerRow: 0,
  dataStartRow: 1,
  sourceHeaders: SOURCE_HEADERS,
  requiredHeaders: REQUIRED_HEADERS,
  fieldMap: FIELD_MAP,
  defaultBranchCode: '',
  defaults: {
    BANKACCOUNT: '1000.02.01',
    CHEQUENO: '',
    CHEQUEDATE: '',
    FISCALPMT: '',
    VOID: '',
    OVERPAYUSED: '',
    APPLYFROMCREDIT: '',
    RETURNCREDIT: '',
    TAXPPH23: '',
    DISCTAKENAMOUNT: '',
    PPH23AMOUNT: '',
    PPH23RATE: '',
    PPH23FISCALRATE: '',
    PPH23NUMBER: '',
  },
};
