const COLUMNS = [
  'INVOICENO','INVOICEDATE','CUSTOMERID','TERMSID','SHIPVIA','WAREHOUSEID','SALESMANID',
  'SHIPTO1','SHIPTO2','SHIPTO3','SHIPTO4','SHIPTO5','DESCRIPTION','SHIPDATE','TAXDATE',
  'PURCHASEORDERNO','TAX1CODE','TAX1RATE','TAX2CODE','TAX2RATE','RATE','INCLUSIVETAX',
  'CUSTOMERISTAXABLE','CASHDISCOUNT','CASHDISCPC','FREIGHT','FISCALRATE','ARACCOUNT',
  'CURRENCYNAME','TAXFORMNUMBER','TAXFORMCODE','DELIVERYORDER','SOID','DOID','ITEMNO',
  'ITEMOVDESC','QUANTITY','ITEMUNIT','UNITRATIO','UNITPRICE','ITEMDISCPC','TAXCODES',
  'WAREHOUSEID_ITEM',
];

module.exports = {
  sheetName: 'Data SI',
  dataStartRow: 2,
  columns: COLUMNS,
  defaultBranchCode: '1142293583',
};
