CREATE TABLE IF NOT EXISTS conversion_batches (
  id varchar(36) NOT NULL,
  batch_name varchar(255) NOT NULL,
  original_folder_name varchar(255) NOT NULL,
  source_format varchar(30) NOT NULL,
  target_format varchar(30) NOT NULL,
  status enum('UPLOADING','VALIDATING','QUEUED','PROCESSING','COMPLETED','REJECTED','FAILED','EXPIRED') NOT NULL DEFAULT 'UPLOADING',
  total_input_files int NOT NULL DEFAULT 0,
  processed_input_files int NOT NULL DEFAULT 0,
  total_output_files int NOT NULL DEFAULT 0,
  total_records bigint NOT NULL DEFAULT 0,
  progress_percent decimal(5,2) NOT NULL DEFAULT 0.00,
  error_message text NULL,
  validation_errors json NULL,
  zip_file_name varchar(255) NULL,
  zip_file_path varchar(1000) NULL,
  zip_size_bytes bigint NULL,
  completed_at datetime NULL,
  expires_at datetime NULL,
  deleted_at datetime NULL,
  created_by varchar(36) NOT NULL,
  created_by_name varchar(255) NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_conversion_batches_created_by (created_by),
  KEY idx_conversion_batches_status (status),
  KEY idx_conversion_batches_expires_at (expires_at),
  KEY idx_conversion_batches_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
